# Generated by Django 4.2.8 on 2025-11-25 02:55

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('logistica', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('trazabilidad', '0001_initial'),
        ('alertas', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='PreferenciasNotificaciones',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('alertas_habilitadas', models.BooleanField(default=True)),
                ('eventos_trazabilidad_habilitados', models.BooleanField(default=True)),
                ('estados_envios_habilitados', models.BooleanField(default=True)),
                ('calidad_habilitada', models.BooleanField(default=True)),
                ('sincronizacion_habilitada', models.BooleanField(default=False)),
                ('sistema_habilitada', models.BooleanField(default=True)),
                ('intervalo_polling_segundos', models.IntegerField(default=300, help_text='Cada cuántos segundos el cliente consulta notificaciones')),
                ('eliminar_notificaciones_leidas_dias', models.IntegerField(default=30)),
                ('silencioso_horario_inicio', models.TimeField(blank=True, help_text='Hora de inicio (HH:MM)', null=True)),
                ('silencioso_horario_fin', models.TimeField(blank=True, help_text='Hora de fin (HH:MM)', null=True)),
                ('actualizado_en', models.DateTimeField(auto_now=True)),
                ('usuario', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='preferencias_notificaciones', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Preferencias Notificaciones',
                'verbose_name_plural': 'Preferencias Notificaciones',
                'db_table': 'preferencias_notificaciones',
            },
        ),
        migrations.CreateModel(
            name='Notificaciones',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('tipo_notificacion', models.CharField(choices=[('ALERTA', 'Alerta'), ('EVENTO_TRAZABILIDAD', 'Evento Trazabilidad'), ('ENVIO_ESTADO', 'Estado de Envío'), ('CALIDAD', 'Control de Calidad'), ('SINCRONIZACION', 'Sincronización'), ('SISTEMA', 'Sistema'), ('INFORMATIVO', 'Informativo')], max_length=50)),
                ('titulo', models.CharField(max_length=255)),
                ('cuerpo', models.TextField()),
                ('prioridad', models.CharField(choices=[('BAJA', 'Baja'), ('MEDIA', 'Media'), ('ALTA', 'Alta'), ('CRITICA', 'Crítica')], default='MEDIA', max_length=20)),
                ('datos_adicionales', models.JSONField(blank=True, default=dict)),
                ('fue_leida', models.BooleanField(default=False)),
                ('fecha_lectura', models.DateTimeField(blank=True, null=True)),
                ('fecha_expiracion', models.DateTimeField(blank=True, help_text='Fecha en que la notificación se elimina', null=True)),
                ('creado_en', models.DateTimeField(auto_now_add=True)),
                ('actualizado_en', models.DateTimeField(auto_now=True)),
                ('alerta', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='notificaciones', to='alertas.alertas')),
                ('envio', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='notificaciones', to='logistica.envios')),
                ('evento_trazabilidad', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='notificaciones', to='trazabilidad.eventostrazabilidad')),
                ('lote', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='notificaciones', to='trazabilidad.lotes')),
                ('usuario_destinatario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notificaciones', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Notificación',
                'verbose_name_plural': 'Notificaciones',
                'db_table': 'notificaciones',
            },
        ),
        migrations.CreateModel(
            name='HistorialLecturaNotifc',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('tipo_dispositivo', models.CharField(choices=[('ANDROID', 'Android'), ('IOS', 'iOS'), ('WEB', 'Web'), ('API', 'API REST')], max_length=20)),
                ('codigo_dispositivo', models.CharField(blank=True, max_length=100, null=True)),
                ('timestamp_lectura', models.DateTimeField(auto_now_add=True)),
                ('ip_dispositivo', models.GenericIPAddressField(blank=True, null=True)),
                ('user_agent', models.TextField(blank=True, null=True)),
                ('notificacion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='historial_lectura', to='notificaciones.notificaciones')),
            ],
            options={
                'verbose_name': 'Historial Lectura Notificación',
                'verbose_name_plural': 'Historiales Lectura Notificaciones',
                'db_table': 'historial_lectura_notificaciones',
            },
        ),
        migrations.AddIndex(
            model_name='notificaciones',
            index=models.Index(fields=['usuario_destinatario', 'fue_leida', 'creado_en'], name='notificacio_usuario_71d292_idx'),
        ),
        migrations.AddIndex(
            model_name='notificaciones',
            index=models.Index(fields=['fue_leida'], name='notificacio_fue_lei_2708e7_idx'),
        ),
        migrations.AddIndex(
            model_name='notificaciones',
            index=models.Index(fields=['prioridad'], name='notificacio_priorid_eb1da5_idx'),
        ),
        migrations.AddIndex(
            model_name='notificaciones',
            index=models.Index(fields=['creado_en'], name='notificacio_creado__94437b_idx'),
        ),
    ]
