# Generated by Django 4.2.8 on 2025-11-25 02:55

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('usuarios', '0001_initial'),
        ('logistica', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('trazabilidad', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='DispositivosSensores',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('codigo_dispositivo', models.CharField(db_index=True, max_length=50, unique=True)),
                ('nombre', models.CharField(max_length=100)),
                ('tipo_dispositivo', models.CharField(choices=[('TEMPERATURA', 'Sensor de Temperatura'), ('HUMEDAD', 'Sensor de Humedad'), ('TEMPERATURA_HUMEDAD', 'Sensor de Temperatura y Humedad'), ('PH', 'Sensor de pH'), ('LUMINOSIDAD', 'Sensor de Luminosidad'), ('HUMEDAD_SUELO', 'Sensor de Humedad de Suelo'), ('PLUVIOMETRO', 'Pluviómetro'), ('ESTACION_METEOROLOGICA', 'Estación Meteorológica'), ('GPS', 'GPS Tracker'), ('OTRO', 'Otro')], max_length=30)),
                ('latitud', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True)),
                ('longitud', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True)),
                ('descripcion_ubicacion', models.CharField(blank=True, max_length=255, null=True)),
                ('fabricante', models.CharField(blank=True, max_length=100, null=True)),
                ('modelo', models.CharField(blank=True, max_length=100, null=True)),
                ('numero_serie', models.CharField(blank=True, max_length=100, null=True)),
                ('firmware_version', models.CharField(blank=True, max_length=50, null=True)),
                ('frecuencia_lectura_minutos', models.IntegerField(default=15, help_text='Frecuencia de lectura en minutos')),
                ('umbral_alerta_min', models.DecimalField(blank=True, decimal_places=2, help_text='Valor mínimo para generar alerta', max_digits=10, null=True)),
                ('umbral_alerta_max', models.DecimalField(blank=True, decimal_places=2, help_text='Valor máximo para generar alerta', max_digits=10, null=True)),
                ('estado', models.CharField(choices=[('ACTIVO', 'Activo'), ('INACTIVO', 'Inactivo'), ('MANTENIMIENTO', 'En Mantenimiento'), ('AVERIADO', 'Averiado'), ('DESINSTALADO', 'Desinstalado')], default='ACTIVO', max_length=20)),
                ('fecha_instalacion', models.DateField(blank=True, null=True)),
                ('fecha_ultimo_mantenimiento', models.DateField(blank=True, null=True)),
                ('fecha_proximo_mantenimiento', models.DateField(blank=True, null=True)),
                ('ultima_lectura_fecha', models.DateTimeField(blank=True, null=True)),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('mac_address', models.CharField(blank=True, max_length=17, null=True)),
                ('configuracion_adicional', models.JSONField(blank=True, default=dict)),
                ('notas', models.TextField(blank=True, null=True)),
                ('creado_en', models.DateTimeField(auto_now_add=True)),
                ('actualizado_en', models.DateTimeField(auto_now=True)),
                ('empresa', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='sensores', to='usuarios.empresas')),
                ('finca', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='sensores', to='usuarios.fincas')),
                ('ubicacion', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sensores', to='logistica.ubicaciones')),
            ],
            options={
                'verbose_name': 'Dispositivo Sensor',
                'verbose_name_plural': 'Dispositivos Sensores',
                'db_table': 'dispositivos_sensores',
                'ordering': ['empresa', 'nombre'],
            },
        ),
        migrations.CreateModel(
            name='ConfiguracionesAlertasSensor',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('tipo_medicion', models.CharField(max_length=30)),
                ('nombre', models.CharField(max_length=100)),
                ('descripcion', models.TextField(blank=True, null=True)),
                ('tipo_condicion', models.CharField(choices=[('MAYOR_QUE', 'Mayor que'), ('MENOR_QUE', 'Menor que'), ('IGUAL_A', 'Igual a'), ('ENTRE', 'Entre rango'), ('FUERA_DE_RANGO', 'Fuera de rango')], max_length=20)),
                ('valor_referencia', models.DecimalField(decimal_places=2, max_digits=10)),
                ('valor_referencia_max', models.DecimalField(blank=True, decimal_places=2, help_text='Para condiciones de rango', max_digits=10, null=True)),
                ('nivel_alerta', models.CharField(choices=[('INFORMATIVA', 'Informativa'), ('ADVERTENCIA', 'Advertencia'), ('CRITICA', 'Crítica')], max_length=20)),
                ('mensaje_alerta', models.TextField()),
                ('enviar_notificacion', models.BooleanField(default=True)),
                ('es_activa', models.BooleanField(default=True)),
                ('creado_en', models.DateTimeField(auto_now_add=True)),
                ('actualizado_en', models.DateTimeField(auto_now=True)),
                ('dispositivo', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='configuraciones_alerta', to='sensores.dispositivossensores')),
                ('empresa', models.ForeignKey(blank=True, help_text='Alerta a nivel empresa (todos sus sensores)', null=True, on_delete=django.db.models.deletion.CASCADE, to='usuarios.empresas')),
                ('usuarios_notificar', models.ManyToManyField(blank=True, related_name='configuraciones_alertas_sensor', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Configuración de Alerta de Sensor',
                'verbose_name_plural': 'Configuraciones de Alertas de Sensores',
                'db_table': 'configuraciones_alertas_sensor',
                'ordering': ['nivel_alerta', 'nombre'],
            },
        ),
        migrations.CreateModel(
            name='RegistrosMantenimientoSensor',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('tipo_mantenimiento', models.CharField(choices=[('PREVENTIVO', 'Mantenimiento Preventivo'), ('CORRECTIVO', 'Mantenimiento Correctivo'), ('CALIBRACION', 'Calibración'), ('ACTUALIZACION_FIRMWARE', 'Actualización de Firmware'), ('REEMPLAZO', 'Reemplazo')], max_length=30)),
                ('fecha_mantenimiento', models.DateField()),
                ('descripcion', models.TextField()),
                ('tecnico_nombre', models.CharField(max_length=100)),
                ('tecnico_empresa', models.CharField(blank=True, max_length=100, null=True)),
                ('costo', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('resultado', models.TextField(blank=True, null=True)),
                ('repuestos_utilizados', models.JSONField(blank=True, default=list)),
                ('proximo_mantenimiento', models.DateField(blank=True, null=True)),
                ('creado_en', models.DateTimeField(auto_now_add=True)),
                ('actualizado_en', models.DateTimeField(auto_now=True)),
                ('dispositivo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='mantenimientos', to='sensores.dispositivossensores')),
                ('registrado_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Registro de Mantenimiento de Sensor',
                'verbose_name_plural': 'Registros de Mantenimiento de Sensores',
                'db_table': 'registros_mantenimiento_sensor',
                'ordering': ['-fecha_mantenimiento'],
                'indexes': [models.Index(fields=['dispositivo', 'fecha_mantenimiento'], name='registros_m_disposi_d552b4_idx')],
            },
        ),
        migrations.CreateModel(
            name='LecturasSensores',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('tipo_medicion', models.CharField(help_text='temperatura, humedad, ph, etc.', max_length=30)),
                ('valor', models.DecimalField(decimal_places=2, max_digits=10)),
                ('unidad_medida', models.CharField(help_text='°C, %, pH, lux, etc.', max_length=20)),
                ('fecha_lectura', models.DateTimeField(db_index=True)),
                ('fuente', models.CharField(choices=[('AUTOMATICA', 'Lectura Automática'), ('MANUAL', 'Lectura Manual'), ('IMPORTADA', 'Importada')], default='AUTOMATICA', max_length=20)),
                ('latitud', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True)),
                ('longitud', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True)),
                ('alerta_generada', models.BooleanField(default=False)),
                ('fuera_de_rango', models.BooleanField(default=False)),
                ('datos_adicionales', models.JSONField(blank=True, default=dict)),
                ('observaciones', models.TextField(blank=True, null=True)),
                ('creado_en', models.DateTimeField(auto_now_add=True)),
                ('dispositivo', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='lecturas', to='sensores.dispositivossensores')),
                ('lote', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='lecturas_sensores', to='trazabilidad.lotes')),
                ('registrado_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='lecturas_manuales', to=settings.AUTH_USER_MODEL)),
                ('transporte', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='lecturas_sensores', to='logistica.transportes')),
                ('ubicacion', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='logistica.ubicaciones')),
            ],
            options={
                'verbose_name': 'Lectura de Sensor',
                'verbose_name_plural': 'Lecturas de Sensores',
                'db_table': 'lecturas_sensores',
                'ordering': ['-fecha_lectura'],
                'indexes': [models.Index(fields=['dispositivo', 'fecha_lectura'], name='lecturas_se_disposi_f03171_idx'), models.Index(fields=['lote', 'fecha_lectura'], name='lecturas_se_lote_id_82a6e2_idx'), models.Index(fields=['transporte', 'fecha_lectura'], name='lecturas_se_transpo_300e4a_idx'), models.Index(fields=['fecha_lectura'], name='lecturas_se_fecha_l_8b8a0a_idx'), models.Index(fields=['alerta_generada'], name='lecturas_se_alerta__d55dc9_idx'), models.Index(fields=['tipo_medicion'], name='lecturas_se_tipo_me_5e2250_idx')],
            },
        ),
        migrations.AddIndex(
            model_name='dispositivossensores',
            index=models.Index(fields=['codigo_dispositivo'], name='dispositivo_codigo__90b8a6_idx'),
        ),
        migrations.AddIndex(
            model_name='dispositivossensores',
            index=models.Index(fields=['empresa', 'estado'], name='dispositivo_empresa_ab45bb_idx'),
        ),
        migrations.AddIndex(
            model_name='dispositivossensores',
            index=models.Index(fields=['tipo_dispositivo'], name='dispositivo_tipo_di_dc0cf4_idx'),
        ),
    ]
