# Generated by Django 4.2.8 on 2025-11-25 02:55

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='EstadosSincronizacion',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('codigo_dispositivo', models.CharField(help_text='Identificador único del dispositivo móvil', max_length=100)),
                ('plataforma', models.CharField(choices=[('ANDROID', 'Android'), ('IOS', 'iOS'), ('WEB', 'Web')], max_length=20)),
                ('version_app', models.CharField(blank=True, max_length=20, null=True)),
                ('version_db_local', models.CharField(blank=True, max_length=20, null=True)),
                ('numero_registros_locales', models.IntegerField(default=0)),
                ('tamaño_db_local_mb', models.FloatField(default=0.0)),
                ('estado', models.CharField(choices=[('SINCRONIZADO', 'Sincronizado'), ('PENDIENTE', 'Pendiente'), ('EN_PROGRESO', 'En Progreso'), ('CONFLICTO', 'Conflicto'), ('ERROR', 'Error')], default='SINCRONIZADO', max_length=20)),
                ('ultimo_sync_exitoso', models.DateTimeField(blank=True, null=True)),
                ('ultimo_sync_intento', models.DateTimeField(blank=True, null=True)),
                ('mensaje_error', models.TextField(blank=True, null=True)),
                ('reintentos', models.IntegerField(default=0)),
                ('creado_en', models.DateTimeField(auto_now_add=True)),
                ('actualizado_en', models.DateTimeField(auto_now=True)),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sincronizaciones', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Estado Sincronización',
                'verbose_name_plural': 'Estados Sincronización',
                'db_table': 'estados_sincronizacion',
                'unique_together': {('usuario', 'codigo_dispositivo')},
            },
        ),
        migrations.CreateModel(
            name='ControlVersionesDB',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('numero_version', models.CharField(max_length=20)),
                ('descripcion_cambios', models.TextField()),
                ('hash_schema', models.CharField(max_length=256)),
                ('fecha_liberacion', models.DateTimeField()),
                ('es_obligatoria', models.BooleanField(default=False)),
                ('creado_en', models.DateTimeField(auto_now_add=True)),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Control Versiones DB',
                'verbose_name_plural': 'Controles Versiones DB',
                'db_table': 'control_versiones_db',
            },
        ),
        migrations.CreateModel(
            name='ConflictosSincronizacion',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('tabla_afectada', models.CharField(max_length=100)),
                ('registro_id', models.CharField(max_length=100)),
                ('dato_cliente', models.JSONField()),
                ('dato_servidor', models.JSONField()),
                ('estrategia_resolucion', models.CharField(choices=[('ULTIMA_ESCRITURA', 'Última Escritura Gana'), ('CLIENTE', 'Versión Cliente'), ('SERVIDOR', 'Versión Servidor'), ('MANUAL', 'Resolución Manual')], default='ULTIMA_ESCRITURA', max_length=20)),
                ('estado_conflicto', models.CharField(choices=[('ABIERTO', 'Abierto'), ('RESUELTO', 'Resuelto'), ('CANCELADO', 'Cancelado')], default='ABIERTO', max_length=20)),
                ('dato_final', models.JSONField(blank=True, null=True)),
                ('detectado_en', models.DateTimeField(auto_now_add=True)),
                ('resuelto_en', models.DateTimeField(blank=True, null=True)),
                ('sincronizacion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='conflictos', to='sincronizacion.estadossincronizacion')),
            ],
            options={
                'verbose_name': 'Conflicto Sincronización',
                'verbose_name_plural': 'Conflictos Sincronización',
                'db_table': 'conflictos_sincronizacion',
            },
        ),
        migrations.CreateModel(
            name='RegistrosSincronizacion',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('tipo_sincronizacion', models.CharField(choices=[('UPLOAD', 'Carga a Servidor'), ('DOWNLOAD', 'Descarga del Servidor'), ('BIDIRECIONAL', 'Bidireccional')], max_length=20)),
                ('registros_procesados', models.IntegerField(default=0)),
                ('registros_exitosos', models.IntegerField(default=0)),
                ('registros_fallidos', models.IntegerField(default=0)),
                ('registros_ignorados', models.IntegerField(default=0)),
                ('datos_transferidos_mb', models.FloatField(default=0.0)),
                ('duracion_segundos', models.FloatField(default=0.0)),
                ('fue_exitosa', models.BooleanField(default=True)),
                ('mensaje', models.TextField(blank=True, null=True)),
                ('timestamp_inicio', models.DateTimeField(auto_now_add=True)),
                ('timestamp_fin', models.DateTimeField(blank=True, null=True)),
                ('sincronizacion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='registros', to='sincronizacion.estadossincronizacion')),
            ],
            options={
                'verbose_name': 'Registro Sincronización',
                'verbose_name_plural': 'Registros Sincronización',
                'db_table': 'registros_sincronizacion',
                'indexes': [models.Index(fields=['sincronizacion', 'timestamp_inicio'], name='registros_s_sincron_844cbc_idx'), models.Index(fields=['timestamp_inicio'], name='registros_s_timesta_c0d7af_idx')],
            },
        ),
    ]
