# Generated by Django 4.2.8 on 2025-11-25 02:55

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='IndicesKPI',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('produccion_total_kg', models.DecimalField(decimal_places=2, default=0, max_digits=20)),
                ('numero_lotes_registrados', models.IntegerField(default=0)),
                ('numero_productos_diferentes', models.IntegerField(default=0)),
                ('porcentaje_aprobados', models.FloatField(default=0.0)),
                ('porcentaje_rechazados', models.FloatField(default=0.0)),
                ('porcentaje_condicionados', models.FloatField(default=0.0)),
                ('entregas_a_tiempo', models.IntegerField(default=0)),
                ('entregas_retrasadas', models.IntegerField(default=0)),
                ('tiempo_promedio_transporte_horas', models.FloatField(default=0.0)),
                ('certificaciones_activas', models.IntegerField(default=0)),
                ('porcentaje_cumplimiento_normativo', models.FloatField(default=0.0)),
                ('incidencias_reportadas', models.IntegerField(default=0)),
                ('fecha_inicio_periodo', models.DateField()),
                ('fecha_fin_periodo', models.DateField()),
                ('calculado_en', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Índice KPI',
                'verbose_name_plural': 'Índices KPI',
                'db_table': 'indices_kpi',
                'indexes': [models.Index(fields=['fecha_inicio_periodo', 'fecha_fin_periodo'], name='indices_kpi_fecha_i_2abac9_idx')],
            },
        ),
        migrations.CreateModel(
            name='DashboardDatos',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('tipo_dashboard', models.CharField(choices=[('PRODUCTOR', 'Dashboard Productor'), ('GERENTE_OPERACIONES', 'Dashboard Gerente Operaciones'), ('GERENTE_CALIDAD', 'Dashboard Gerente Calidad'), ('ADMIN_SISTEMA', 'Dashboard Administrador')], max_length=50)),
                ('datos', models.JSONField(default=dict)),
                ('fecha_ultima_actualizacion', models.DateTimeField(auto_now=True)),
                ('creado_en', models.DateTimeField(auto_now_add=True)),
                ('usuario', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Dashboard Datos',
                'verbose_name_plural': 'Dashboards Datos',
                'db_table': 'dashboard_datos',
            },
        ),
        migrations.CreateModel(
            name='Reportes',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=255)),
                ('descripcion', models.TextField(blank=True, null=True)),
                ('tipo_reporte', models.CharField(choices=[('TRAZABILIDAD', 'Trazabilidad de Lote'), ('PRODUCCION', 'Producción Total'), ('CALIDAD', 'Control de Calidad'), ('LOGISTICA', 'Logística y Transporte'), ('KPI', 'Indicadores Clave de Desempeño'), ('EXPORTACION', 'Exportaciones'), ('CUMPLIMIENTO', 'Cumplimiento Normativo'), ('EFICIENCIA', 'Eficiencia Operacional'), ('PERSONALIZADO', 'Personalizado')], max_length=50)),
                ('fecha_inicio', models.DateField()),
                ('fecha_fin', models.DateField()),
                ('filtros_aplicados', models.JSONField(blank=True, default=dict)),
                ('datos_reporte', models.JSONField(default=dict)),
                ('archivo_generado', models.FileField(blank=True, null=True, upload_to='reportes/')),
                ('formato_exportacion', models.CharField(choices=[('PDF', 'PDF'), ('CSV', 'CSV'), ('EXCEL', 'Excel'), ('JSON', 'JSON')], default='PDF', max_length=20)),
                ('creado_en', models.DateTimeField(auto_now_add=True)),
                ('actualizado_en', models.DateTimeField(auto_now=True)),
                ('usuario_creador', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Reporte',
                'verbose_name_plural': 'Reportes',
                'db_table': 'reportes',
                'indexes': [models.Index(fields=['usuario_creador', 'creado_en'], name='reportes_usuario_64c294_idx'), models.Index(fields=['tipo_reporte'], name='reportes_tipo_re_d41df6_idx')],
            },
        ),
    ]
