# Generated by Django 4.2.8 on 2025-11-25 02:55

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('autenticacion', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Empresas',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=255, unique=True)),
                ('tipo_empresa', models.CharField(choices=[('PRODUCTOR', 'Productor Agrícola'), ('ACOPIO', 'Centro de Acopio'), ('TRANSFORMACION', 'Empresa de Transformación'), ('EXPORTADOR', 'Empresa Exportadora'), ('DISTRIBUIDOR', 'Distribuidor'), ('ASOCIACION', 'Asociación Productiva')], max_length=50)),
                ('registro_nacional', models.CharField(blank=True, max_length=50, null=True, unique=True)),
                ('email', models.EmailField(max_length=254)),
                ('telefono', models.CharField(blank=True, max_length=20, null=True)),
                ('direccion', models.TextField()),
                ('ciudad', models.CharField(max_length=100)),
                ('pais', models.CharField(default='Ecuador', max_length=100)),
                ('es_activa', models.BooleanField(default=True)),
                ('certificaciones_info', models.JSONField(blank=True, default=list, help_text='Información general de certificaciones')),
                ('creado_en', models.DateTimeField(auto_now_add=True)),
                ('actualizado_en', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Empresa',
                'verbose_name_plural': 'Empresas',
                'db_table': 'empresas',
            },
        ),
        migrations.CreateModel(
            name='Fincas',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=255)),
                ('codigo_finca', models.CharField(max_length=50, unique=True)),
                ('direccion', models.TextField()),
                ('ciudad', models.CharField(max_length=100)),
                ('coordenadas_latitud', models.FloatField()),
                ('coordenadas_longitud', models.FloatField()),
                ('tamaño_hectareas', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('es_activa', models.BooleanField(default=True)),
                ('creado_en', models.DateTimeField(auto_now_add=True)),
                ('actualizado_en', models.DateTimeField(auto_now=True)),
                ('empresa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='fincas', to='usuarios.empresas')),
            ],
            options={
                'verbose_name': 'Finca',
                'verbose_name_plural': 'Fincas',
                'db_table': 'fincas',
            },
        ),
        migrations.CreateModel(
            name='Permisos',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=100, unique=True)),
                ('descripcion', models.TextField(blank=True)),
                ('codigo', models.CharField(help_text='Ej: crear_lote, editar_evento', max_length=50, unique=True)),
            ],
            options={
                'verbose_name': 'Permiso',
                'verbose_name_plural': 'Permisos',
                'db_table': 'permisos',
            },
        ),
        migrations.CreateModel(
            name='UsuariosEmpresas',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('es_responsable', models.BooleanField(default=False, help_text='Si es responsable/gerente de la empresa')),
                ('fecha_asignacion', models.DateTimeField(auto_now_add=True)),
                ('empresa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='usuarios', to='usuarios.empresas')),
                ('finca', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='usuarios.fincas')),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='empresas', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Usuario Empresa',
                'verbose_name_plural': 'Usuarios Empresas',
                'db_table': 'usuarios_empresas',
            },
        ),
        migrations.CreateModel(
            name='RolesPermisos',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('permiso', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='usuarios.permisos')),
                ('rol', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='permisos', to='autenticacion.roles')),
            ],
            options={
                'verbose_name': 'Rol Permiso',
                'verbose_name_plural': 'Roles Permisos',
                'db_table': 'roles_permisos',
            },
        ),
        migrations.AddIndex(
            model_name='empresas',
            index=models.Index(fields=['nombre'], name='empresas_nombre_7f64b8_idx'),
        ),
        migrations.AddIndex(
            model_name='empresas',
            index=models.Index(fields=['tipo_empresa'], name='empresas_tipo_em_8a5e39_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='usuariosempresas',
            unique_together={('usuario', 'empresa')},
        ),
        migrations.AlterUniqueTogether(
            name='rolespermisos',
            unique_together={('rol', 'permiso')},
        ),
        migrations.AlterUniqueTogether(
            name='fincas',
            unique_together={('empresa', 'codigo_finca')},
        ),
    ]
