# Generated by Django 4.2.8 on 2025-11-25 02:55

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('usuarios', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Permisos',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('nombre_permiso', models.CharField(max_length=100, unique=True)),
                ('codigo_permiso', models.CharField(db_index=True, max_length=50, unique=True)),
                ('descripcion', models.TextField(blank=True, null=True)),
                ('tipo_permiso', models.CharField(choices=[('LECTURA', 'Lectura'), ('ESCRITURA', 'Escritura'), ('ELIMINACION', 'Eliminación'), ('ADMINISTRACION', 'Administración'), ('ESPECIAL', 'Especial')], max_length=20)),
                ('modulo', models.CharField(help_text='Módulo al que pertenece (usuarios, lotes, etc)', max_length=50)),
                ('recurso', models.CharField(help_text='Recurso específico dentro del módulo', max_length=50)),
                ('es_activo', models.BooleanField(default=True)),
                ('es_critico', models.BooleanField(default=False, help_text='Permiso crítico que requiere mayor control')),
                ('creado_en', models.DateTimeField(auto_now_add=True)),
                ('actualizado_en', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Permiso',
                'verbose_name_plural': 'Permisos',
                'db_table': 'permisos_extendidos',
                'ordering': ['modulo', 'recurso', 'tipo_permiso'],
            },
        ),
        migrations.CreateModel(
            name='Roles',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('nombre_rol', models.CharField(max_length=50, unique=True)),
                ('codigo_rol', models.CharField(db_index=True, max_length=30, unique=True)),
                ('descripcion', models.TextField(blank=True, null=True)),
                ('tipo_rol', models.CharField(choices=[('SISTEMA', 'Rol del Sistema'), ('PERSONALIZADO', 'Rol Personalizado')], default='PERSONALIZADO', max_length=20)),
                ('es_activo', models.BooleanField(default=True)),
                ('nivel_acceso', models.IntegerField(default=1, help_text='Nivel de acceso jerárquico (1=básico, 10=administrador)')),
                ('creado_en', models.DateTimeField(auto_now_add=True)),
                ('actualizado_en', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Rol',
                'verbose_name_plural': 'Roles',
                'db_table': 'roles_extendidos',
                'ordering': ['-nivel_acceso', 'nombre_rol'],
            },
        ),
        migrations.CreateModel(
            name='UsuariosRoles',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('es_activo', models.BooleanField(default=True)),
                ('fecha_inicio', models.DateTimeField(auto_now_add=True)),
                ('fecha_fin', models.DateTimeField(blank=True, null=True)),
                ('motivo', models.TextField(blank=True, null=True)),
                ('asignado_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='roles_que_asigno', to=settings.AUTH_USER_MODEL)),
                ('empresa', models.ForeignKey(blank=True, help_text='Si el rol aplica solo a una empresa específica', null=True, on_delete=django.db.models.deletion.CASCADE, to='usuarios.empresas')),
                ('finca', models.ForeignKey(blank=True, help_text='Si el rol aplica solo a una finca específica', null=True, on_delete=django.db.models.deletion.CASCADE, to='usuarios.fincas')),
                ('rol', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='usuarios_asignados', to='roles_permisos.roles')),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='roles_asignados', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Usuario-Rol',
                'verbose_name_plural': 'Usuarios-Roles',
                'db_table': 'usuarios_roles_extendidos',
            },
        ),
        migrations.CreateModel(
            name='RolesPermisos',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('fecha_asignacion', models.DateTimeField(auto_now_add=True)),
                ('concedido_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('permiso', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='roles_asociados', to='roles_permisos.permisos')),
                ('rol', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='permisos_asociados', to='roles_permisos.roles')),
            ],
            options={
                'verbose_name': 'Rol-Permiso',
                'verbose_name_plural': 'Roles-Permisos',
                'db_table': 'roles_permisos_extendidos',
            },
        ),
        migrations.CreateModel(
            name='PermisosEspeciales',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('tipo', models.CharField(choices=[('CONCEDIDO', 'Permiso Concedido'), ('DENEGADO', 'Permiso Denegado')], max_length=20)),
                ('es_activo', models.BooleanField(default=True)),
                ('fecha_inicio', models.DateTimeField(auto_now_add=True)),
                ('fecha_fin', models.DateTimeField(blank=True, null=True)),
                ('motivo', models.TextField()),
                ('concedido_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='permisos_especiales_que_concedio', to=settings.AUTH_USER_MODEL)),
                ('empresa', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='usuarios.empresas')),
                ('permiso', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='roles_permisos.permisos')),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='permisos_especiales', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Permiso Especial',
                'verbose_name_plural': 'Permisos Especiales',
                'db_table': 'permisos_especiales',
            },
        ),
        migrations.AddIndex(
            model_name='permisos',
            index=models.Index(fields=['modulo', 'recurso'], name='permisos_ex_modulo_2996c5_idx'),
        ),
        migrations.AddIndex(
            model_name='permisos',
            index=models.Index(fields=['codigo_permiso'], name='permisos_ex_codigo__9ab8c4_idx'),
        ),
        migrations.AddIndex(
            model_name='usuariosroles',
            index=models.Index(fields=['usuario', 'es_activo'], name='usuarios_ro_usuario_9d948d_idx'),
        ),
        migrations.AddIndex(
            model_name='usuariosroles',
            index=models.Index(fields=['rol'], name='usuarios_ro_rol_id_4605ae_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='usuariosroles',
            unique_together={('usuario', 'rol', 'empresa', 'finca')},
        ),
        migrations.AlterUniqueTogether(
            name='rolespermisos',
            unique_together={('rol', 'permiso')},
        ),
        migrations.AddIndex(
            model_name='permisosespeciales',
            index=models.Index(fields=['usuario', 'es_activo'], name='permisos_es_usuario_46164d_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='permisosespeciales',
            unique_together={('usuario', 'permiso', 'empresa')},
        ),
    ]
