# Generated by Django 4.2.8 on 2025-11-25 02:55

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('usuarios', '0001_initial'),
        ('trazabilidad', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ResultadosAnalisisLaboratorio',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('tipo_analisis', models.CharField(help_text='Ej: Análisis Microbiológico, Residuos de Pesticidas', max_length=100)),
                ('laboratorio', models.CharField(max_length=255)),
                ('fecha_muestreo', models.DateTimeField()),
                ('fecha_resultado', models.DateTimeField()),
                ('parametros_medidos', models.JSONField(blank=True, default=dict, help_text="Ej: {E_coli: '< 10 UFC/g', Listeria: 'Ausente'}")),
                ('resultado_general', models.CharField(choices=[('CUMPLE', 'Cumple'), ('NO_CUMPLE', 'No Cumple')], default='PENDIENTE', max_length=50)),
                ('numero_informe', models.CharField(max_length=100, unique=True)),
                ('documento_informe', models.FileField(upload_to='analisis_laboratorio/')),
                ('observaciones', models.TextField(blank=True, null=True)),
                ('creado_en', models.DateTimeField(auto_now_add=True)),
                ('empresa', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='usuarios.empresas')),
                ('lote', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='analisis_laboratorio', to='trazabilidad.lotes')),
            ],
            options={
                'verbose_name': 'Resultado Análisis Laboratorio',
                'verbose_name_plural': 'Resultados Análisis Laboratorio',
                'db_table': 'resultados_analisis_laboratorio',
            },
        ),
        migrations.CreateModel(
            name='CertificacionesEstandares',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('tipo_certificacion', models.CharField(choices=[('GLOBALG_A_P', 'GlobalG.A.P'), ('AGROCALIDAD', 'AGROCALIDAD'), ('ORGANICO', 'Orgánico'), ('BPA', 'Buenas Prácticas Agrícolas'), ('FSSC22000', 'FSSC 22000'), ('OTRA', 'Otra')], max_length=50)),
                ('numero_certificado', models.CharField(max_length=100, unique=True)),
                ('fecha_emision', models.DateField()),
                ('fecha_vencimiento', models.DateField()),
                ('organismo_certificador', models.CharField(max_length=255)),
                ('auditor', models.CharField(blank=True, max_length=255)),
                ('documento_certificado', models.FileField(upload_to='certificaciones/')),
                ('es_valida', models.BooleanField(default=True)),
                ('observaciones', models.TextField(blank=True, null=True)),
                ('creado_en', models.DateTimeField(auto_now_add=True)),
                ('empresa', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='usuarios.empresas')),
                ('lote', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='certificaciones', to='trazabilidad.lotes')),
            ],
            options={
                'verbose_name': 'Certificación Estándar',
                'verbose_name_plural': 'Certificaciones Estándares',
                'db_table': 'certificaciones_estandares',
            },
        ),
        migrations.CreateModel(
            name='ProcesosProcesamiento',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('tipo_proceso', models.CharField(choices=[('LAVADO', 'Lavado'), ('CLASIFICACION', 'Clasificación'), ('EMPAQUETADO', 'Empaquetado'), ('TRANSFORMACION', 'Transformación'), ('CONGELACION', 'Congelación'), ('DESHIDRATACION', 'Deshidratación'), ('OTRO', 'Otro')], max_length=50)),
                ('descripcion', models.TextField()),
                ('fecha_inicio', models.DateTimeField()),
                ('fecha_fin', models.DateTimeField(blank=True, null=True)),
                ('temperatura_promedio', models.FloatField(blank=True, null=True)),
                ('humedad_promedio', models.FloatField(blank=True, null=True)),
                ('tiempo_duracion_minutos', models.IntegerField(blank=True, null=True)),
                ('resultado_proceso', models.JSONField(blank=True, default=dict)),
                ('observaciones', models.TextField(blank=True, null=True)),
                ('creado_en', models.DateTimeField(auto_now_add=True)),
                ('actualizado_en', models.DateTimeField(auto_now=True)),
                ('empresa', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='usuarios.empresas')),
                ('lote', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='procesos', to='trazabilidad.lotes')),
                ('usuario_responsable', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Proceso Procesamiento',
                'verbose_name_plural': 'Procesos Procesamiento',
                'db_table': 'procesos_procesamiento',
                'indexes': [models.Index(fields=['lote', 'fecha_inicio'], name='procesos_pr_lote_id_2c76a8_idx'), models.Index(fields=['empresa', 'fecha_inicio'], name='procesos_pr_empresa_a5867e_idx')],
            },
        ),
        migrations.CreateModel(
            name='InspeccionesCalidad',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('tipo_inspeccion', models.CharField(help_text='Ej: Inspección Sensorial, Análisis Físico', max_length=100)),
                ('fecha_inspeccion', models.DateTimeField()),
                ('resultado', models.CharField(choices=[('APROBADO', 'Aprobado'), ('RECHAZADO', 'Rechazado'), ('CONDICIONADO', 'Condicionado'), ('PENDIENTE', 'Pendiente')], default='PENDIENTE', max_length=20)),
                ('porcentaje_rechazo', models.FloatField(default=0.0, help_text='Porcentaje de producto rechazado')),
                ('criterios_evaluados', models.JSONField(blank=True, default=dict, help_text="Ej: {color: 'cumple', textura: 'cumple', olor: 'no_cumple'}")),
                ('observaciones', models.TextField(blank=True, null=True)),
                ('recomendaciones', models.TextField(blank=True, null=True)),
                ('creado_en', models.DateTimeField(auto_now_add=True)),
                ('actualizado_en', models.DateTimeField(auto_now=True)),
                ('empresa', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='usuarios.empresas')),
                ('inspector', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('lote', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='inspecciones', to='trazabilidad.lotes')),
            ],
            options={
                'verbose_name': 'Inspección Calidad',
                'verbose_name_plural': 'Inspecciones Calidad',
                'db_table': 'inspecciones_calidad',
                'indexes': [models.Index(fields=['lote', 'fecha_inspeccion'], name='inspeccione_lote_id_64df73_idx'), models.Index(fields=['resultado'], name='inspeccione_resulta_8ea75b_idx')],
            },
        ),
    ]
