# Generated by Django 4.2.8 on 2025-11-25 02:55

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('usuarios', '0001_initial'),
        ('trazabilidad', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Certificaciones',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=100, unique=True)),
                ('codigo', models.CharField(db_index=True, max_length=30, unique=True)),
                ('tipo_certificacion', models.CharField(choices=[('CALIDAD', 'Calidad'), ('ORGANICO', 'Orgánico'), ('AMBIENTAL', 'Ambiental'), ('SOCIAL', 'Social'), ('INOCUIDAD', 'Inocuidad Alimentaria'), ('BPA', 'Buenas Prácticas Agrícolas'), ('BPM', 'Buenas Prácticas de Manufactura'), ('COMERCIO_JUSTO', 'Comercio Justo'), ('OTRO', 'Otro')], max_length=30)),
                ('entidad_emisora', models.CharField(max_length=100)),
                ('alcance', models.CharField(choices=[('INTERNACIONAL', 'Internacional'), ('NACIONAL', 'Nacional'), ('REGIONAL', 'Regional')], max_length=20)),
                ('descripcion', models.TextField(blank=True, null=True)),
                ('requisitos_generales', models.JSONField(blank=True, default=dict, help_text='Lista de requisitos generales para obtener la certificación')),
                ('url_informacion', models.URLField(blank=True, null=True)),
                ('logo_url', models.URLField(blank=True, null=True)),
                ('vigencia_anios', models.IntegerField(default=1, help_text='Años de vigencia de la certificación')),
                ('es_activa', models.BooleanField(default=True)),
                ('creado_en', models.DateTimeField(auto_now_add=True)),
                ('actualizado_en', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Certificación',
                'verbose_name_plural': 'Certificaciones',
                'db_table': 'certificaciones',
                'ordering': ['nombre'],
            },
        ),
        migrations.CreateModel(
            name='RequisitosCumplimiento',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('codigo_requisito', models.CharField(db_index=True, max_length=50, unique=True)),
                ('nombre', models.CharField(max_length=200)),
                ('normativa', models.CharField(blank=True, max_length=100, null=True)),
                ('pais_destino', models.CharField(blank=True, max_length=50, null=True)),
                ('descripcion', models.TextField()),
                ('tipo_requisito', models.CharField(choices=[('DOCUMENTACION', 'Documentación'), ('ANALISIS', 'Análisis de Laboratorio'), ('INSPECCION', 'Inspección'), ('REGISTRO', 'Registro'), ('PROCESO', 'Proceso Específico'), ('TRAZABILIDAD', 'Trazabilidad'), ('OTRO', 'Otro')], max_length=30)),
                ('es_obligatorio', models.BooleanField(default=True)),
                ('frecuencia_verificacion', models.CharField(choices=[('UNICA_VEZ', 'Única Vez'), ('POR_LOTE', 'Por Lote'), ('MENSUAL', 'Mensual'), ('TRIMESTRAL', 'Trimestral'), ('SEMESTRAL', 'Semestral'), ('ANUAL', 'Anual')], max_length=20)),
                ('documentacion_requerida', models.JSONField(blank=True, default=list, help_text='Lista de documentos requeridos')),
                ('parametros_analisis', models.JSONField(blank=True, default=dict, help_text='Parámetros específicos si es un análisis')),
                ('es_activo', models.BooleanField(default=True)),
                ('creado_en', models.DateTimeField(auto_now_add=True)),
                ('actualizado_en', models.DateTimeField(auto_now=True)),
                ('certificacion', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='requisitos', to='certificaciones.certificaciones')),
            ],
            options={
                'verbose_name': 'Requisito de Cumplimiento',
                'verbose_name_plural': 'Requisitos de Cumplimiento',
                'db_table': 'requisitos_cumplimiento',
                'ordering': ['normativa', 'nombre'],
            },
        ),
        migrations.CreateModel(
            name='CumplimientoNormativo',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('cumplido', models.BooleanField()),
                ('fecha_verificacion', models.DateTimeField()),
                ('evidencia_url', models.URLField(blank=True, null=True)),
                ('archivo_evidencia', models.FileField(blank=True, null=True, upload_to='cumplimiento/')),
                ('numero_referencia', models.CharField(blank=True, help_text='Número de certificado, análisis, etc.', max_length=100, null=True)),
                ('observaciones', models.TextField(blank=True, null=True)),
                ('datos_verificacion', models.JSONField(blank=True, default=dict, help_text='Datos específicos de la verificación')),
                ('creado_en', models.DateTimeField(auto_now_add=True)),
                ('actualizado_en', models.DateTimeField(auto_now=True)),
                ('lote', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cumplimientos', to='trazabilidad.lotes')),
                ('requisito', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='cumplimientos', to='certificaciones.requisitoscumplimiento')),
                ('verificado_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Cumplimiento Normativo',
                'verbose_name_plural': 'Cumplimientos Normativos',
                'db_table': 'cumplimiento_normativo',
                'ordering': ['-fecha_verificacion'],
            },
        ),
        migrations.CreateModel(
            name='CertificacionesProductores',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('numero_certificado', models.CharField(db_index=True, max_length=100, unique=True)),
                ('fecha_emision', models.DateField()),
                ('fecha_expiracion', models.DateField()),
                ('estado', models.CharField(choices=[('VIGENTE', 'Vigente'), ('POR_RENOVAR', 'Por Renovar'), ('VENCIDA', 'Vencida'), ('SUSPENDIDA', 'Suspendida'), ('REVOCADA', 'Revocada'), ('EN_TRAMITE', 'En Trámite')], default='VIGENTE', max_length=20)),
                ('archivo_certificado', models.FileField(blank=True, null=True, upload_to='certificaciones/')),
                ('alcance_productos', models.JSONField(blank=True, default=list, help_text='Lista de productos cubiertos por esta certificación')),
                ('alcance_procesos', models.JSONField(blank=True, default=list, help_text='Lista de procesos cubiertos')),
                ('fecha_ultima_auditoria', models.DateField(blank=True, null=True)),
                ('fecha_proxima_auditoria', models.DateField(blank=True, null=True)),
                ('auditor_nombre', models.CharField(blank=True, max_length=100, null=True)),
                ('observaciones', models.TextField(blank=True, null=True)),
                ('condiciones_especiales', models.TextField(blank=True, null=True)),
                ('creado_en', models.DateTimeField(auto_now_add=True)),
                ('actualizado_en', models.DateTimeField(auto_now=True)),
                ('certificacion', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='productores_certificados', to='certificaciones.certificaciones')),
                ('finca', models.ForeignKey(blank=True, help_text='Certificación específica para una finca', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='certificaciones', to='usuarios.fincas')),
                ('productor', models.ForeignKey(blank=True, limit_choices_to={'tipo_empresa__in': ['PRODUCTOR', 'ASOCIACION']}, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='certificaciones_obtenidas', to='usuarios.empresas')),
            ],
            options={
                'verbose_name': 'Certificación de Productor',
                'verbose_name_plural': 'Certificaciones de Productores',
                'db_table': 'certificaciones_productores',
                'ordering': ['-fecha_emision'],
            },
        ),
        migrations.CreateModel(
            name='CertificacionesLotes',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('verificado', models.BooleanField(default=False)),
                ('fecha_verificacion', models.DateTimeField(blank=True, null=True)),
                ('archivo_evidencia', models.FileField(blank=True, null=True, upload_to='certificaciones/evidencias/')),
                ('observaciones', models.TextField(blank=True, null=True)),
                ('creado_en', models.DateTimeField(auto_now_add=True)),
                ('certificacion_productor', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='lotes_certificados', to='certificaciones.certificacionesproductores')),
                ('lote', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='certificaciones_aplicadas', to='trazabilidad.lotes')),
                ('verificado_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Certificación de Lote',
                'verbose_name_plural': 'Certificaciones de Lotes',
                'db_table': 'certificaciones_lotes',
            },
        ),
        migrations.AddIndex(
            model_name='requisitoscumplimiento',
            index=models.Index(fields=['normativa'], name='requisitos__normati_73949d_idx'),
        ),
        migrations.AddIndex(
            model_name='requisitoscumplimiento',
            index=models.Index(fields=['pais_destino'], name='requisitos__pais_de_d395c1_idx'),
        ),
        migrations.AddIndex(
            model_name='requisitoscumplimiento',
            index=models.Index(fields=['codigo_requisito'], name='requisitos__codigo__e3b0a3_idx'),
        ),
        migrations.AddIndex(
            model_name='cumplimientonormativo',
            index=models.Index(fields=['lote', 'cumplido'], name='cumplimient_lote_id_d6e0e6_idx'),
        ),
        migrations.AddIndex(
            model_name='cumplimientonormativo',
            index=models.Index(fields=['requisito'], name='cumplimient_requisi_83b081_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='cumplimientonormativo',
            unique_together={('lote', 'requisito')},
        ),
        migrations.AddIndex(
            model_name='certificacionesproductores',
            index=models.Index(fields=['estado', 'fecha_expiracion'], name='certificaci_estado_6c0a84_idx'),
        ),
        migrations.AddIndex(
            model_name='certificacionesproductores',
            index=models.Index(fields=['numero_certificado'], name='certificaci_numero__f3c5d7_idx'),
        ),
        migrations.AddIndex(
            model_name='certificacionesproductores',
            index=models.Index(fields=['productor', 'estado'], name='certificaci_product_accd2e_idx'),
        ),
        migrations.AddIndex(
            model_name='certificacioneslotes',
            index=models.Index(fields=['lote'], name='certificaci_lote_id_e10b92_idx'),
        ),
        migrations.AddIndex(
            model_name='certificacioneslotes',
            index=models.Index(fields=['verificado'], name='certificaci_verific_6a19bc_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='certificacioneslotes',
            unique_together={('lote', 'certificacion_productor')},
        ),
    ]
