# Generated by Django 4.2.8 on 2025-11-25 02:55

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('usuarios', '0001_initial'),
        ('trazabilidad', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Conductores',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('numero_licencia', models.CharField(max_length=50, unique=True)),
                ('categoria_licencia', models.CharField(default='C', max_length=10)),
                ('fecha_vencimiento_licencia', models.DateField()),
                ('es_activo', models.BooleanField(default=True)),
                ('creado_en', models.DateTimeField(auto_now_add=True)),
                ('empresa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='conductores', to='usuarios.empresas')),
                ('usuario', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Conductor',
                'verbose_name_plural': 'Conductores',
                'db_table': 'conductores',
            },
        ),
        migrations.CreateModel(
            name='Envios',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('latitud_origen', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True)),
                ('longitud_origen', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True)),
                ('nombre_origen', models.CharField(max_length=255)),
                ('latitud_destino', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True)),
                ('longitud_destino', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True)),
                ('nombre_destino', models.CharField(max_length=255)),
                ('fecha_salida', models.DateTimeField(blank=True, null=True)),
                ('fecha_llegada_estimada', models.DateTimeField(blank=True, null=True)),
                ('fecha_llegada_real', models.DateTimeField(blank=True, null=True)),
                ('temperatura_registrada', models.FloatField(blank=True, null=True)),
                ('humedad_registrada', models.FloatField(blank=True, null=True)),
                ('distancia_km', models.FloatField(blank=True, null=True)),
                ('estado', models.CharField(choices=[('PENDIENTE', 'Pendiente'), ('EN_TRANSITO', 'En Tránsito'), ('ENTREGADO', 'Entregado'), ('CANCELADO', 'Cancelado'), ('DEVUELTO', 'Devuelto')], default='PENDIENTE', max_length=20)),
                ('observaciones', models.TextField(blank=True, null=True)),
                ('incidencias', models.TextField(blank=True, null=True)),
                ('creado_en', models.DateTimeField(auto_now_add=True)),
                ('actualizado_en', models.DateTimeField(auto_now=True)),
                ('conductor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='logistica.conductores')),
                ('lote', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='envios', to='trazabilidad.lotes')),
            ],
            options={
                'verbose_name': 'Envío',
                'verbose_name_plural': 'Envíos',
                'db_table': 'envios',
            },
        ),
        migrations.CreateModel(
            name='Vehiculos',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('placa', models.CharField(max_length=20, unique=True)),
                ('tipo_vehiculo', models.CharField(choices=[('CAMION', 'Camión'), ('FURGONETA', 'Furgoneta'), ('AUTO', 'Automóvil'), ('MOTO', 'Motocicleta'), ('OTRO', 'Otro')], max_length=20)),
                ('marca', models.CharField(max_length=100)),
                ('modelo', models.CharField(max_length=100)),
                ('año_fabricacion', models.IntegerField()),
                ('capacidad_kg', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('capacidad_volumen_m3', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('es_refrigerado', models.BooleanField(default=False)),
                ('temperatura_min', models.FloatField(blank=True, help_text='Temperatura mínima en °C', null=True)),
                ('temperatura_max', models.FloatField(blank=True, help_text='Temperatura máxima en °C', null=True)),
                ('estado', models.CharField(choices=[('DISPONIBLE', 'Disponible'), ('EN_TRANSITO', 'En Tránsito'), ('EN_MANTENIMIENTO', 'En Mantenimiento'), ('FUERA_SERVICIO', 'Fuera de Servicio')], default='DISPONIBLE', max_length=20)),
                ('numero_seguro', models.CharField(blank=True, max_length=100, null=True)),
                ('fecha_vencimiento_seguro', models.DateField(blank=True, null=True)),
                ('creado_en', models.DateTimeField(auto_now_add=True)),
                ('actualizado_en', models.DateTimeField(auto_now=True)),
                ('empresa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='vehiculos', to='usuarios.empresas')),
            ],
            options={
                'verbose_name': 'Vehículo',
                'verbose_name_plural': 'Vehículos',
                'db_table': 'vehiculos',
            },
        ),
        migrations.CreateModel(
            name='Ubicaciones',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=255)),
                ('tipo_ubicacion', models.CharField(choices=[('ALMACEN', 'Almacén'), ('CAMPO', 'Campo'), ('PLANTA', 'Planta de Procesamiento'), ('VEHICULO', 'Vehículo'), ('CLIENTE', 'Cliente'), ('OTRO', 'Otro')], max_length=20)),
                ('descripcion', models.TextField(blank=True, null=True)),
                ('latitud', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True)),
                ('longitud', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True)),
                ('direccion', models.TextField(blank=True, null=True)),
                ('ciudad', models.CharField(blank=True, max_length=100, null=True)),
                ('pais', models.CharField(default='Ecuador', max_length=100)),
                ('es_activa', models.BooleanField(default=True)),
                ('creado_en', models.DateTimeField(auto_now_add=True)),
                ('actualizado_en', models.DateTimeField(auto_now=True)),
                ('empresa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ubicaciones', to='usuarios.empresas')),
            ],
            options={
                'verbose_name': 'Ubicación',
                'verbose_name_plural': 'Ubicaciones',
                'db_table': 'ubicaciones',
            },
        ),
        migrations.CreateModel(
            name='Transportes',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('codigo_transporte', models.CharField(max_length=100, unique=True)),
                ('tipo_transporte', models.CharField(choices=[('LOTE', 'Transporte de Lote'), ('INSUMO', 'Transporte de Insumo'), ('PRODUCTO', 'Transporte de Producto'), ('OTRO', 'Otro')], max_length=20)),
                ('estado', models.CharField(choices=[('PROGRAMADO', 'Programado'), ('EN_RUTA', 'En Ruta'), ('COMPLETADO', 'Completado'), ('CANCELADO', 'Cancelado')], default='PROGRAMADO', max_length=20)),
                ('fecha_programada', models.DateTimeField()),
                ('fecha_inicio', models.DateTimeField(blank=True, null=True)),
                ('fecha_fin', models.DateTimeField(blank=True, null=True)),
                ('descripcion_carga', models.TextField(blank=True, null=True)),
                ('peso_kg', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('observaciones', models.TextField(blank=True, null=True)),
                ('creado_en', models.DateTimeField(auto_now_add=True)),
                ('actualizado_en', models.DateTimeField(auto_now=True)),
                ('conductor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='logistica.conductores')),
                ('empresa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='transportes', to='usuarios.empresas')),
                ('ubicacion_destino', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='transportes_destino', to='logistica.ubicaciones')),
                ('ubicacion_origen', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='transportes_origen', to='logistica.ubicaciones')),
                ('vehiculo', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='logistica.vehiculos')),
            ],
            options={
                'verbose_name': 'Transporte',
                'verbose_name_plural': 'Transportes',
                'db_table': 'transportes',
            },
        ),
        migrations.CreateModel(
            name='RuteTrackingActual',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('latitud', models.DecimalField(decimal_places=6, max_digits=9)),
                ('longitud', models.DecimalField(decimal_places=6, max_digits=9)),
                ('temperatura', models.FloatField(blank=True, null=True)),
                ('humedad', models.FloatField(blank=True, null=True)),
                ('velocidad_kmh', models.FloatField(blank=True, null=True)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('observaciones', models.TextField(blank=True, null=True)),
                ('envio', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tracking', to='logistica.envios')),
            ],
            options={
                'verbose_name': 'Rastreo de Ruta',
                'verbose_name_plural': 'Rastreos de Rutas',
                'db_table': 'rute_tracking_actual',
            },
        ),
        migrations.AddField(
            model_name='envios',
            name='vehiculo',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='logistica.vehiculos'),
        ),
        migrations.CreateModel(
            name='AlertasLogistica',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('tipo_alerta', models.CharField(choices=[('RETRASO', 'Retraso'), ('TEMPERATURA', 'Variación de Temperatura'), ('DESVIACION_RUTA', 'Desviación de Ruta'), ('AVERIA', 'Avería del Vehículo'), ('OTRO', 'Otro')], max_length=50)),
                ('estado_alerta', models.CharField(choices=[('ACTIVA', 'Activa'), ('RESUELTA', 'Resuelta'), ('CANCELADA', 'Cancelada')], default='ACTIVA', max_length=20)),
                ('descripcion', models.TextField()),
                ('fecha_alerta', models.DateTimeField(auto_now_add=True)),
                ('fecha_resolucion', models.DateTimeField(blank=True, null=True)),
                ('accion_tomada', models.TextField(blank=True, null=True)),
                ('envio', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='alertas', to='logistica.envios')),
            ],
            options={
                'verbose_name': 'Alerta Logística',
                'verbose_name_plural': 'Alertas Logística',
                'db_table': 'alertas_logistica',
            },
        ),
        migrations.AddIndex(
            model_name='vehiculos',
            index=models.Index(fields=['placa'], name='vehiculos_placa_0848cc_idx'),
        ),
        migrations.AddIndex(
            model_name='vehiculos',
            index=models.Index(fields=['empresa', 'estado'], name='vehiculos_empresa_5aed20_idx'),
        ),
        migrations.AddIndex(
            model_name='ubicaciones',
            index=models.Index(fields=['empresa', 'tipo_ubicacion'], name='ubicaciones_empresa_db945d_idx'),
        ),
        migrations.AddIndex(
            model_name='transportes',
            index=models.Index(fields=['codigo_transporte'], name='transportes_codigo__3bacb2_idx'),
        ),
        migrations.AddIndex(
            model_name='transportes',
            index=models.Index(fields=['empresa', 'estado'], name='transportes_empresa_18e883_idx'),
        ),
        migrations.AddIndex(
            model_name='rutetrackingactual',
            index=models.Index(fields=['envio', 'timestamp'], name='rute_tracki_envio_i_ae5af1_idx'),
        ),
        migrations.AddIndex(
            model_name='envios',
            index=models.Index(fields=['lote', 'fecha_salida'], name='envios_lote_id_fee3c9_idx'),
        ),
        migrations.AddIndex(
            model_name='envios',
            index=models.Index(fields=['estado'], name='envios_estado_889713_idx'),
        ),
        migrations.AddIndex(
            model_name='envios',
            index=models.Index(fields=['fecha_salida'], name='envios_fecha_s_088cc0_idx'),
        ),
    ]
