# Generated by Django 4.2.8 on 2025-11-25 02:55

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='SesionesUsuario',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('token_sesion', models.CharField(max_length=255, unique=True)),
                ('ip_origen', models.GenericIPAddressField()),
                ('user_agent', models.TextField()),
                ('dispositivo', models.CharField(blank=True, max_length=100, null=True)),
                ('pais', models.CharField(blank=True, max_length=100, null=True)),
                ('ciudad', models.CharField(blank=True, max_length=100, null=True)),
                ('fecha_inicio', models.DateTimeField(auto_now_add=True)),
                ('fecha_ultima_actividad', models.DateTimeField(auto_now=True)),
                ('fecha_cierre', models.DateTimeField(blank=True, null=True)),
                ('estado', models.CharField(choices=[('ACTIVA', 'Activa'), ('CERRADA', 'Cerrada'), ('EXPIRADA', 'Expirada'), ('FORZADA_CIERRE', 'Forzada a Cerrar')], default='ACTIVA', max_length=20)),
                ('metadatos', models.JSONField(blank=True, default=dict)),
            ],
            options={
                'verbose_name': 'Sesión de Usuario',
                'verbose_name_plural': 'Sesiones de Usuario',
                'db_table': 'sesiones_usuario',
                'ordering': ['-fecha_inicio'],
            },
        ),
    ]
