# Generated by Django 4.2.8 on 2025-11-25 02:55

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auditoria', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='sesionesusuario',
            name='usuario',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sesiones', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddIndex(
            model_name='sesionesusuario',
            index=models.Index(fields=['usuario', 'estado'], name='sesiones_us_usuario_818d62_idx'),
        ),
        migrations.AddIndex(
            model_name='sesionesusuario',
            index=models.Index(fields=['token_sesion'], name='sesiones_us_token_s_eadc2b_idx'),
        ),
        migrations.AddIndex(
            model_name='sesionesusuario',
            index=models.Index(fields=['fecha_inicio'], name='sesiones_us_fecha_i_7da908_idx'),
        ),
    ]
