# Generated by Django 4.2.8 on 2025-11-25 02:55

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BackupsSistema',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('tipo_backup', models.CharField(choices=[('COMPLETO', 'Backup Completo'), ('INCREMENTAL', 'Backup Incremental'), ('DIFERENCIAL', 'Backup Diferencial')], max_length=20)),
                ('estado', models.CharField(choices=[('EXITOSO', 'Exitoso'), ('EN_PROGRESO', 'En Progreso'), ('FALLIDO', 'Fallido')], max_length=20)),
                ('fecha_inicio', models.DateTimeField(auto_now_add=True)),
                ('fecha_fin', models.DateTimeField(blank=True, null=True)),
                ('tamaño_mb', models.FloatField(blank=True, null=True)),
                ('ubicacion_almacenamiento', models.CharField(help_text='S3, Google Cloud, etc', max_length=500)),
                ('duracion_minutos', models.FloatField(blank=True, null=True)),
                ('error_mensaje', models.TextField(blank=True, null=True)),
            ],
            options={
                'verbose_name': 'Backup Sistema',
                'verbose_name_plural': 'Backups Sistema',
                'db_table': 'backups_sistema',
            },
        ),
        migrations.CreateModel(
            name='ConfiguracionSistema',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('productos_permitidos', models.JSONField(blank=True, default=list, help_text='Lista de IDs de productos permitidos')),
                ('tipos_eventos_permitidos', models.JSONField(blank=True, default=list, help_text='Lista de IDs de tipos de eventos permitidos')),
                ('unidades_medida', models.JSONField(blank=True, default=dict, help_text='Mapeo de unidades de medida')),
                ('intervalo_sincronizacion_minutos', models.IntegerField(default=30)),
                ('intervalo_notificaciones_minutos', models.IntegerField(default=5)),
                ('tamaño_maximo_documento_mb', models.IntegerField(default=50)),
                ('dias_retencion_documentos', models.IntegerField(default=2555, help_text='7 años por defecto')),
                ('intentos_fallidos_max', models.IntegerField(default=5)),
                ('bloqueo_minutos', models.IntegerField(default=15)),
                ('sesion_duracion_horas', models.IntegerField(default=8)),
                ('actualizado_en', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Configuración Sistema',
                'verbose_name_plural': 'Configuración Sistema',
                'db_table': 'configuracion_sistema',
            },
        ),
        migrations.CreateModel(
            name='LogsAcceso',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('tipo_acceso', models.CharField(choices=[('EXITOSO', 'Exitoso'), ('FALLIDO', 'Fallido'), ('BLOQUEADO', 'Bloqueado')], max_length=20)),
                ('ip_origen', models.GenericIPAddressField()),
                ('user_agent', models.TextField(blank=True, null=True)),
                ('motivo_fallo', models.CharField(blank=True, max_length=255, null=True)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Log Acceso',
                'verbose_name_plural': 'Logs Acceso',
                'db_table': 'logs_acceso',
            },
        ),
        migrations.CreateModel(
            name='LogsActividad',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('tipo_actividad', models.CharField(choices=[('CREATE', 'Crear'), ('UPDATE', 'Actualizar'), ('DELETE', 'Eliminar'), ('VIEW', 'Visualizar'), ('EXPORT', 'Exportar'), ('IMPORT', 'Importar')], max_length=20)),
                ('modulo', models.CharField(max_length=100)),
                ('entidad', models.CharField(max_length=100)),
                ('registro_id', models.CharField(blank=True, max_length=100, null=True)),
                ('descripcion', models.TextField(blank=True, null=True)),
                ('datos_antes', models.JSONField(blank=True, null=True)),
                ('datos_despues', models.JSONField(blank=True, null=True)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Log Actividad',
                'verbose_name_plural': 'Logs Actividad',
                'db_table': 'logs_actividad',
            },
        ),
    ]
