# Generated by Django 4.2.8 on 2025-11-25 02:55

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('administracion', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='logsactividad',
            name='usuario',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='logsacceso',
            name='usuario',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddIndex(
            model_name='backupssistema',
            index=models.Index(fields=['fecha_inicio'], name='backups_sis_fecha_i_bf6a0f_idx'),
        ),
        migrations.AddIndex(
            model_name='logsactividad',
            index=models.Index(fields=['usuario', 'timestamp'], name='logs_activi_usuario_221c46_idx'),
        ),
        migrations.AddIndex(
            model_name='logsactividad',
            index=models.Index(fields=['modulo'], name='logs_activi_modulo_88cde2_idx'),
        ),
        migrations.AddIndex(
            model_name='logsactividad',
            index=models.Index(fields=['timestamp'], name='logs_activi_timesta_d3adef_idx'),
        ),
        migrations.AddIndex(
            model_name='logsacceso',
            index=models.Index(fields=['usuario', 'timestamp'], name='logs_acceso_usuario_f7b497_idx'),
        ),
        migrations.AddIndex(
            model_name='logsacceso',
            index=models.Index(fields=['timestamp'], name='logs_acceso_timesta_e250a4_idx'),
        ),
    ]
