# Generated by Django 4.2.8 on 2025-11-25 02:55

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('logistica', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('trazabilidad', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Clientes',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('nombre_comercial', models.CharField(max_length=255)),
                ('razon_social', models.CharField(blank=True, max_length=255, null=True)),
                ('tipo_cliente', models.CharField(choices=[('DISTRIBUIDOR', 'Distribuidor'), ('EXPORTADOR', 'Exportador'), ('INDUSTRIA', 'Industria Procesadora'), ('RETAIL', 'Retail/Supermercado'), ('MAYORISTA', 'Mayorista'), ('MINORISTA', 'Minorista'), ('CONSUMIDOR_FINAL', 'Consumidor Final'), ('OTRO', 'Otro')], max_length=30)),
                ('categoria', models.CharField(choices=[('A', 'Categoría A - Premium'), ('B', 'Categoría B - Regular'), ('C', 'Categoría C - Ocasional')], default='B', max_length=1)),
                ('identificacion_fiscal', models.CharField(help_text='RUC, RFC, Tax ID, etc.', max_length=50, unique=True)),
                ('email', models.EmailField(max_length=254)),
                ('telefono', models.CharField(max_length=20)),
                ('telefono_alternativo', models.CharField(blank=True, max_length=20, null=True)),
                ('direccion', models.TextField()),
                ('ciudad', models.CharField(max_length=100)),
                ('provincia_estado', models.CharField(max_length=100)),
                ('pais', models.CharField(max_length=100)),
                ('codigo_postal', models.CharField(blank=True, max_length=20, null=True)),
                ('limite_credito', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('dias_credito', models.IntegerField(default=0, help_text='Días de crédito otorgados')),
                ('descuento_porcentaje', models.DecimalField(decimal_places=2, default=0, help_text='Descuento habitual en porcentaje', max_digits=5)),
                ('contacto_nombre', models.CharField(blank=True, max_length=100, null=True)),
                ('contacto_cargo', models.CharField(blank=True, max_length=100, null=True)),
                ('contacto_email', models.EmailField(blank=True, max_length=254, null=True)),
                ('contacto_telefono', models.CharField(blank=True, max_length=20, null=True)),
                ('certificaciones_requeridas', models.JSONField(blank=True, default=list, help_text='Lista de certificaciones que requiere')),
                ('requisitos_especiales', models.TextField(blank=True, null=True)),
                ('es_activo', models.BooleanField(default=True)),
                ('fecha_primer_contacto', models.DateField(blank=True, null=True)),
                ('fecha_primera_venta', models.DateField(blank=True, null=True)),
                ('notas', models.TextField(blank=True, null=True)),
                ('creado_en', models.DateTimeField(auto_now_add=True)),
                ('actualizado_en', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Cliente',
                'verbose_name_plural': 'Clientes',
                'db_table': 'clientes',
                'ordering': ['nombre_comercial'],
            },
        ),
        migrations.CreateModel(
            name='Ventas',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('numero_venta', models.CharField(db_index=True, max_length=50, unique=True)),
                ('numero_factura', models.CharField(blank=True, max_length=50, null=True)),
                ('fecha_venta', models.DateField()),
                ('fecha_entrega_estimada', models.DateField(blank=True, null=True)),
                ('fecha_entrega_real', models.DateField(blank=True, null=True)),
                ('estado', models.CharField(choices=[('COTIZACION', 'Cotización'), ('CONFIRMADA', 'Confirmada'), ('EN_PREPARACION', 'En Preparación'), ('ENVIADA', 'Enviada'), ('ENTREGADA', 'Entregada'), ('FACTURADA', 'Facturada'), ('CANCELADA', 'Cancelada')], default='COTIZACION', max_length=20)),
                ('condicion_pago', models.CharField(choices=[('CONTADO', 'Contado'), ('CREDITO_15', 'Crédito 15 días'), ('CREDITO_30', 'Crédito 30 días'), ('CREDITO_60', 'Crédito 60 días'), ('CREDITO_90', 'Crédito 90 días'), ('ANTICIPO_50', 'Anticipo 50%'), ('ANTICIPO_100', 'Anticipo 100%')], default='CONTADO', max_length=20)),
                ('incoterm', models.CharField(blank=True, choices=[('EXW', 'EXW - Ex Works'), ('FCA', 'FCA - Free Carrier'), ('FOB', 'FOB - Free On Board'), ('CIF', 'CIF - Cost Insurance Freight'), ('DAP', 'DAP - Delivered at Place'), ('DDP', 'DDP - Delivered Duty Paid')], max_length=10, null=True)),
                ('subtotal', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('descuento', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('impuestos', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('total', models.DecimalField(decimal_places=2, max_digits=12)),
                ('moneda', models.CharField(default='USD', max_length=3)),
                ('direccion_entrega', models.TextField(blank=True, null=True)),
                ('observaciones', models.TextField(blank=True, null=True)),
                ('terminos_condiciones', models.TextField(blank=True, null=True)),
                ('metadata_adicional', models.JSONField(blank=True, default=dict)),
                ('creado_en', models.DateTimeField(auto_now_add=True)),
                ('actualizado_en', models.DateTimeField(auto_now=True)),
                ('cliente', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='ventas', to='clientes.clientes')),
                ('transporte_asignado', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ventas', to='logistica.transportes')),
                ('vendedor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ventas_realizadas', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Venta',
                'verbose_name_plural': 'Ventas',
                'db_table': 'ventas',
                'ordering': ['-fecha_venta', '-numero_venta'],
            },
        ),
        migrations.CreateModel(
            name='HistorialInteraccionesCliente',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('tipo_interaccion', models.CharField(choices=[('LLAMADA', 'Llamada Telefónica'), ('EMAIL', 'Correo Electrónico'), ('REUNION', 'Reunión'), ('VISITA', 'Visita a Cliente'), ('COTIZACION', 'Envío de Cotización'), ('RECLAMO', 'Reclamo'), ('SEGUIMIENTO', 'Seguimiento'), ('OTRO', 'Otro')], max_length=20)),
                ('fecha_interaccion', models.DateTimeField()),
                ('asunto', models.CharField(max_length=255)),
                ('descripcion', models.TextField()),
                ('requiere_seguimiento', models.BooleanField(default=False)),
                ('fecha_seguimiento', models.DateField(blank=True, null=True)),
                ('seguimiento_completado', models.BooleanField(default=False)),
                ('archivos_adjuntos', models.JSONField(blank=True, default=list)),
                ('creado_en', models.DateTimeField(auto_now_add=True)),
                ('cliente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='interacciones', to='clientes.clientes')),
                ('usuario', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Interacción con Cliente',
                'verbose_name_plural': 'Interacciones con Clientes',
                'db_table': 'historial_interacciones_cliente',
                'ordering': ['-fecha_interaccion'],
            },
        ),
        migrations.CreateModel(
            name='DetallesVenta',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('cantidad', models.DecimalField(decimal_places=2, max_digits=10)),
                ('unidad_medida', models.CharField(max_length=20)),
                ('precio_unitario', models.DecimalField(decimal_places=2, max_digits=10)),
                ('descuento_porcentaje', models.DecimalField(decimal_places=2, default=0, max_digits=5)),
                ('descuento_monto', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('subtotal', models.DecimalField(decimal_places=2, max_digits=12)),
                ('descripcion', models.TextField(blank=True, null=True)),
                ('notas', models.TextField(blank=True, null=True)),
                ('creado_en', models.DateTimeField(auto_now_add=True)),
                ('lote', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='ventas', to='trazabilidad.lotes')),
                ('venta', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='detalles', to='clientes.ventas')),
            ],
            options={
                'verbose_name': 'Detalle de Venta',
                'verbose_name_plural': 'Detalles de Venta',
                'db_table': 'detalles_venta',
                'ordering': ['venta', 'creado_en'],
            },
        ),
        migrations.CreateModel(
            name='Cotizaciones',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('numero_cotizacion', models.CharField(db_index=True, max_length=50, unique=True)),
                ('fecha_cotizacion', models.DateField()),
                ('fecha_validez', models.DateField()),
                ('estado', models.CharField(choices=[('BORRADOR', 'Borrador'), ('ENVIADA', 'Enviada al Cliente'), ('ACEPTADA', 'Aceptada'), ('RECHAZADA', 'Rechazada'), ('VENCIDA', 'Vencida'), ('CONVERTIDA', 'Convertida a Venta')], default='BORRADOR', max_length=20)),
                ('total', models.DecimalField(decimal_places=2, max_digits=12)),
                ('moneda', models.CharField(default='USD', max_length=3)),
                ('condiciones_pago', models.CharField(blank=True, max_length=20, null=True)),
                ('tiempo_entrega_dias', models.IntegerField(blank=True, null=True)),
                ('observaciones', models.TextField(blank=True, null=True)),
                ('creado_en', models.DateTimeField(auto_now_add=True)),
                ('actualizado_en', models.DateTimeField(auto_now=True)),
                ('cliente', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='cotizaciones', to='clientes.clientes')),
                ('vendedor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('venta_generada', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='cotizacion_origen', to='clientes.ventas')),
            ],
            options={
                'verbose_name': 'Cotización',
                'verbose_name_plural': 'Cotizaciones',
                'db_table': 'cotizaciones',
                'ordering': ['-fecha_cotizacion'],
            },
        ),
        migrations.AddIndex(
            model_name='clientes',
            index=models.Index(fields=['identificacion_fiscal'], name='clientes_identif_79c72a_idx'),
        ),
        migrations.AddIndex(
            model_name='clientes',
            index=models.Index(fields=['tipo_cliente', 'es_activo'], name='clientes_tipo_cl_d37073_idx'),
        ),
        migrations.AddIndex(
            model_name='clientes',
            index=models.Index(fields=['pais', 'ciudad'], name='clientes_pais_70da79_idx'),
        ),
        migrations.AddIndex(
            model_name='ventas',
            index=models.Index(fields=['numero_venta'], name='ventas_numero__d43a36_idx'),
        ),
        migrations.AddIndex(
            model_name='ventas',
            index=models.Index(fields=['cliente', 'estado'], name='ventas_cliente_d36f13_idx'),
        ),
        migrations.AddIndex(
            model_name='ventas',
            index=models.Index(fields=['fecha_venta'], name='ventas_fecha_v_df623b_idx'),
        ),
        migrations.AddIndex(
            model_name='ventas',
            index=models.Index(fields=['estado'], name='ventas_estado_505824_idx'),
        ),
        migrations.AddIndex(
            model_name='historialinteraccionescliente',
            index=models.Index(fields=['cliente', 'fecha_interaccion'], name='historial_i_cliente_f740e8_idx'),
        ),
        migrations.AddIndex(
            model_name='historialinteraccionescliente',
            index=models.Index(fields=['tipo_interaccion'], name='historial_i_tipo_in_d45434_idx'),
        ),
        migrations.AddIndex(
            model_name='historialinteraccionescliente',
            index=models.Index(fields=['requiere_seguimiento'], name='historial_i_requier_57a636_idx'),
        ),
        migrations.AddIndex(
            model_name='cotizaciones',
            index=models.Index(fields=['numero_cotizacion'], name='cotizacione_numero__e967de_idx'),
        ),
        migrations.AddIndex(
            model_name='cotizaciones',
            index=models.Index(fields=['cliente', 'estado'], name='cotizacione_cliente_f19296_idx'),
        ),
    ]
