# Generated by Django 4.2.8 on 2025-11-25 02:55

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('trazabilidad', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='FotosProductos',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('imagen', models.ImageField(upload_to='fotos_productos/')),
                ('descripcion', models.TextField(blank=True, null=True)),
                ('tipo_foto', models.CharField(choices=[('INICIAL', 'Foto Inicial'), ('PROCESAMIENTO', 'Durante Procesamiento'), ('FINAL', 'Foto Final'), ('INSPECCION', 'Inspección'), ('TRANSPORTE', 'Transporte')], max_length=50)),
                ('latitud', models.FloatField(blank=True, null=True)),
                ('longitud', models.FloatField(blank=True, null=True)),
                ('fecha_foto', models.DateTimeField(auto_now_add=True)),
                ('fotógrafo', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('lote', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='fotos', to='trazabilidad.lotes')),
            ],
            options={
                'verbose_name': 'Foto Producto',
                'verbose_name_plural': 'Fotos Productos',
                'db_table': 'fotos_productos',
            },
        ),
        migrations.CreateModel(
            name='Documentos',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('tipo_documento', models.CharField(choices=[('CERTIFICADO', 'Certificado'), ('RESULTADO_LABORATORIO', 'Resultado de Laboratorio'), ('FACTURA', 'Factura'), ('GUIA_TRANSPORTE', 'Guía de Transporte'), ('FOTO', 'Foto'), ('INFORME', 'Informe'), ('REPORTE_INSPECCION', 'Reporte de Inspección'), ('OTRO', 'Otro')], max_length=50)),
                ('nombre', models.CharField(max_length=255)),
                ('descripcion', models.TextField(blank=True, null=True)),
                ('archivo', models.FileField(max_length=500, upload_to='documentos/')),
                ('tipo_archivo', models.CharField(max_length=20)),
                ('tamaño_bytes', models.BigIntegerField(blank=True, null=True)),
                ('estado', models.CharField(choices=[('PENDIENTE', 'Pendiente'), ('VALIDADO', 'Validado'), ('RECHAZADO', 'Rechazado'), ('ARCHIVADO', 'Archivado')], default='PENDIENTE', max_length=20)),
                ('es_autentico', models.BooleanField(default=False)),
                ('hash_documento', models.CharField(blank=True, help_text='SHA-256 para verificación', max_length=256, null=True)),
                ('fecha_documento', models.DateField(blank=True, null=True)),
                ('fecha_vencimiento', models.DateField(blank=True, null=True)),
                ('numero_referencia', models.CharField(blank=True, max_length=100, null=True)),
                ('fecha_validacion', models.DateTimeField(blank=True, null=True)),
                ('comentarios_validacion', models.TextField(blank=True, null=True)),
                ('creado_en', models.DateTimeField(auto_now_add=True)),
                ('actualizado_en', models.DateTimeField(auto_now=True)),
                ('evento_trazabilidad', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='documentos', to='trazabilidad.eventostrazabilidad')),
                ('lote', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='documentos', to='trazabilidad.lotes')),
                ('subido_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='documentos_subidos', to=settings.AUTH_USER_MODEL)),
                ('usuario', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('validado_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='documentos_validados', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Documento',
                'verbose_name_plural': 'Documentos',
                'db_table': 'documentos',
                'indexes': [models.Index(fields=['lote'], name='documentos_lote_id_095230_idx'), models.Index(fields=['evento_trazabilidad'], name='documentos_evento__55b99f_idx'), models.Index(fields=['tipo_documento'], name='documentos_tipo_do_b6f232_idx'), models.Index(fields=['estado'], name='documentos_estado_2ab89e_idx')],
            },
        ),
    ]
