# Generated by Django 4.2.8 on 2025-11-25 02:55

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Productos',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=100, unique=True)),
                ('tipo_producto', models.CharField(choices=[('FRUTA', 'Fruta'), ('VERDURA', 'Verdura'), ('TUBÉRCULO', 'Tubérculo'), ('GRANO', 'Grano'), ('PROCESADO', 'Producto Procesado')], max_length=50)),
                ('descripcion', models.TextField(blank=True, null=True)),
                ('unidad_medida', models.CharField(default='kg', max_length=20)),
                ('creado_en', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Producto',
                'verbose_name_plural': 'Productos',
                'db_table': 'productos',
            },
        ),
        migrations.CreateModel(
            name='TiposEventosTrazabilidad',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=100, unique=True)),
                ('categoria', models.CharField(choices=[('PRODUCCION', 'Producción'), ('INSPECCION', 'Inspección'), ('PROCESAMIENTO', 'Procesamiento'), ('TRANSPORTE', 'Transporte'), ('ALMACENAMIENTO', 'Almacenamiento'), ('CALIDAD', 'Control de Calidad'), ('EXPORTACION', 'Exportación'), ('RECEPCION', 'Recepción')], max_length=30)),
                ('descripcion', models.TextField(blank=True, null=True)),
                ('requiere_documento', models.BooleanField(default=False)),
                ('requiere_foto', models.BooleanField(default=False)),
                ('requiere_gps', models.BooleanField(default=False)),
            ],
            options={
                'verbose_name': 'Tipo de Evento Trazabilidad',
                'verbose_name_plural': 'Tipos de Eventos Trazabilidad',
                'db_table': 'tipos_eventos_trazabilidad',
            },
        ),
        migrations.CreateModel(
            name='Lotes',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('codigo_lote', models.CharField(db_index=True, max_length=100, unique=True)),
                ('cantidad', models.DecimalField(decimal_places=2, max_digits=15)),
                ('unidad_medida', models.CharField(max_length=20)),
                ('latitud_origen', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True)),
                ('longitud_origen', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True)),
                ('nombre_ubicacion_origen', models.CharField(blank=True, max_length=255, null=True)),
                ('fecha_produccion', models.DateTimeField()),
                ('fecha_empaque', models.DateTimeField(blank=True, null=True)),
                ('fecha_vencimiento', models.DateTimeField(blank=True, null=True)),
                ('estado', models.CharField(choices=[('PRODUCCION', 'En Producción'), ('ALMACENADO', 'Almacenado'), ('TRANSITO', 'En Tránsito'), ('PROCESAMIENTO', 'En Procesamiento'), ('CALIDAD_PENDIENTE', 'Calidad Pendiente'), ('CALIDAD_RECHAZADO', 'Calidad Rechazado'), ('EXPORTACION', 'Exportado'), ('ENTREGADO', 'Entregado'), ('CANCELADO', 'Cancelado')], default='PRODUCCION', max_length=30)),
                ('es_organico', models.BooleanField(default=False)),
                ('temperatura_almacenamiento', models.FloatField(blank=True, help_text='En grados Celsius', null=True)),
                ('humedad_almacenamiento', models.FloatField(blank=True, help_text='En porcentaje', null=True)),
                ('creado_en', models.DateTimeField(auto_now_add=True)),
                ('actualizado_en', models.DateTimeField(auto_now=True)),
                ('qr_code', models.ImageField(blank=True, null=True, upload_to='qr_codes/')),
                ('producto', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='lotes', to='trazabilidad.productos')),
            ],
            options={
                'verbose_name': 'Lote',
                'verbose_name_plural': 'Lotes',
                'db_table': 'lotes',
            },
        ),
        migrations.CreateModel(
            name='HistorialEstadosLote',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('estado_anterior', models.CharField(max_length=30)),
                ('estado_nuevo', models.CharField(max_length=30)),
                ('motivo', models.TextField(blank=True, null=True)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('lote', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cambios_estado', to='trazabilidad.lotes')),
                ('usuario', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Historial Estados Lote',
                'verbose_name_plural': 'Historiales Estados Lote',
                'db_table': 'historial_estados_lote',
            },
        ),
        migrations.CreateModel(
            name='EventosTrazabilidad',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('latitud', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True)),
                ('longitud', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True)),
                ('nombre_ubicacion', models.CharField(blank=True, max_length=255, null=True)),
                ('descripcion', models.TextField()),
                ('fecha_evento', models.DateTimeField()),
                ('observaciones', models.TextField(blank=True, null=True)),
                ('temperatura_registrada', models.FloatField(blank=True, null=True)),
                ('humedad_registrada', models.FloatField(blank=True, null=True)),
                ('timestamp_registro', models.DateTimeField(auto_now_add=True)),
                ('es_sincronizado', models.BooleanField(default=False, help_text='Indica si viene del dispositivo móvil')),
                ('lote', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='eventos', to='trazabilidad.lotes')),
                ('tipo_evento', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='trazabilidad.tiposeventostrazabilidad')),
                ('usuario', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Evento Trazabilidad',
                'verbose_name_plural': 'Eventos Trazabilidad',
                'db_table': 'eventos_trazabilidad',
            },
        ),
        migrations.AddIndex(
            model_name='lotes',
            index=models.Index(fields=['codigo_lote'], name='lotes_codigo__211d52_idx'),
        ),
        migrations.AddIndex(
            model_name='lotes',
            index=models.Index(fields=['estado'], name='lotes_estado_a6768b_idx'),
        ),
        migrations.AddIndex(
            model_name='lotes',
            index=models.Index(fields=['fecha_produccion'], name='lotes_fecha_p_be08cd_idx'),
        ),
        migrations.AddIndex(
            model_name='lotes',
            index=models.Index(fields=['producto', 'estado'], name='lotes_product_882089_idx'),
        ),
        migrations.AddIndex(
            model_name='historialestadoslote',
            index=models.Index(fields=['lote', 'timestamp'], name='historial_e_lote_id_f09ac0_idx'),
        ),
        migrations.AddIndex(
            model_name='historialestadoslote',
            index=models.Index(fields=['timestamp'], name='historial_e_timesta_9e58fb_idx'),
        ),
        migrations.AddIndex(
            model_name='eventostrazabilidad',
            index=models.Index(fields=['lote', 'fecha_evento'], name='eventos_tra_lote_id_34be5d_idx'),
        ),
        migrations.AddIndex(
            model_name='eventostrazabilidad',
            index=models.Index(fields=['tipo_evento', 'fecha_evento'], name='eventos_tra_tipo_ev_60a00d_idx'),
        ),
        migrations.AddIndex(
            model_name='eventostrazabilidad',
            index=models.Index(fields=['timestamp_registro'], name='eventos_tra_timesta_e07da7_idx'),
        ),
    ]
