# Generated by Django 4.2.8 on 2025-11-25 02:55

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Alertas',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('titulo', models.CharField(max_length=255)),
                ('descripcion', models.TextField()),
                ('valor_actual', models.CharField(max_length=255)),
                ('valor_umbral', models.CharField(max_length=255)),
                ('estado', models.CharField(choices=[('ABIERTA', 'Abierta'), ('RECONOCIDA', 'Reconocida'), ('RESUELTA', 'Resuelta'), ('FALSA_ALARMA', 'Falsa Alarma')], default='ABIERTA', max_length=20)),
                ('severidad', models.CharField(choices=[('BAJA', 'Baja'), ('MEDIA', 'Media'), ('ALTA', 'Alta'), ('CRITICA', 'Crítica')], max_length=20)),
                ('fecha_resolucion', models.DateTimeField(blank=True, null=True)),
                ('comentario_resolucion', models.TextField(blank=True, null=True)),
                ('accion_tomada', models.TextField(blank=True, null=True)),
                ('creado_en', models.DateTimeField(auto_now_add=True)),
                ('actualizado_en', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Alerta',
                'verbose_name_plural': 'Alertas',
                'db_table': 'alertas',
            },
        ),
        migrations.CreateModel(
            name='ReglasAlertas',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=255)),
                ('descripcion', models.TextField(blank=True, null=True)),
                ('es_activa', models.BooleanField(default=True)),
                ('tipo_alerta', models.CharField(help_text='Ej: Temperatura Anómala, Retraso en Entrega', max_length=100)),
                ('campo_monitoreado', models.CharField(help_text='Campo del modelo a monitorear', max_length=100)),
                ('operador', models.CharField(choices=[('IGUAL', '='), ('NO_IGUAL', '!='), ('MAYOR_QUE', '>'), ('MENOR_QUE', '<'), ('MAYOR_IGUAL', '>='), ('MENOR_IGUAL', '<='), ('CONTIENE', 'Contiene')], max_length=20)),
                ('valor_comparacion', models.CharField(max_length=255)),
                ('severidad', models.CharField(choices=[('BAJA', 'Baja'), ('MEDIA', 'Media'), ('ALTA', 'Alta'), ('CRITICA', 'Crítica')], default='MEDIA', max_length=20)),
                ('notificar_roles', models.JSONField(blank=True, default=list, help_text='Lista de IDs de roles a notificar')),
                ('notificar_usuarios', models.JSONField(blank=True, default=list, help_text='Lista de IDs de usuarios a notificar')),
                ('creado_en', models.DateTimeField(auto_now_add=True)),
                ('actualizado_en', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Regla Alerta',
                'verbose_name_plural': 'Reglas Alertas',
                'db_table': 'reglas_alertas',
            },
        ),
    ]
