# Generated by Django 4.2.8 on 2025-11-25 02:55

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('logistica', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('trazabilidad', '0001_initial'),
        ('alertas', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='alertas',
            name='envio',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='alertas_generales', to='logistica.envios'),
        ),
        migrations.AddField(
            model_name='alertas',
            name='lote',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='alertas_generales', to='trazabilidad.lotes'),
        ),
        migrations.AddField(
            model_name='alertas',
            name='regla',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='alertas.reglasalertas'),
        ),
        migrations.AddField(
            model_name='alertas',
            name='usuario_asignado',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='alertas_asignadas', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddIndex(
            model_name='alertas',
            index=models.Index(fields=['estado'], name='alertas_estado_62a016_idx'),
        ),
        migrations.AddIndex(
            model_name='alertas',
            index=models.Index(fields=['severidad'], name='alertas_severid_6b75e5_idx'),
        ),
        migrations.AddIndex(
            model_name='alertas',
            index=models.Index(fields=['creado_en'], name='alertas_creado__73197e_idx'),
        ),
        migrations.AddIndex(
            model_name='alertas',
            index=models.Index(fields=['usuario_asignado'], name='alertas_usuario_56c740_idx'),
        ),
    ]
